version: 1.0.{build}
image: Previous Ubuntu1804
platform: x86
install:
- sh: >-
    ls -al

    sudo apt-get update

    sudo apt-get build-essential
build_script:
- sh: make Makefile
test_script:
- sh: ./dist/main.sim